export const API_METHODS = {
  GET: 'get',
  POST: 'post',
  PUT: 'put',
  DELETE: 'delete',
  PATCH: 'patch',
};

export const AUTH = {

  SET_LANGUAGE:"SET_LANGUAGE",
  UPDATE_CLINIC_ID:"UPDATE_CLINIC_ID",
  UPDATE_JOB_DETAIL:'UPDATE_JOB_DETAIL',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',

  UPDATE_ACCOUNT_REQUEST:'UPDATE_ACCOUNT_REQUEST',
  UPDATE_ACCOUNT_SUCCESS:'UPDATE_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT_FAIL:'UPDATE_ACCOUNT_FAIL',

  CLEAR_ERROR_STATUS:'CLEAR_ERROR_STATUS',
  CLEAR_RESPONSE_STATUS:'CLEAR_RESPONSE_STATUS',
  CLEAR_ERROR_STATUS_FORGOT_PASSWORD:'CLEAR_ERROR_STATUS_FORGOT_PASSWORD',

  LOGOUT_USER:'LOGOUT_USER',
};

export const BANK={

  BANK_FORM_REQUEST: 'BANK_FORM_REQUEST',
  BANK_FORM_SUCCESS: 'BANK_FORM_SUCCESS',
  BANK_FORM_FAIL: 'BANK_FORM_FAIL',
  CLEAR_BANK_STATUS:'CLEAR_BANK_STATUS'
}

export const CONTRACT={

  CONTRACT_REQUEST: 'CONTRACT_REQUEST',
  CONTRACT_SUCCESS: 'CONTRACT_SUCCESS',
  CONTRACT_FAIL: 'CONTRACT_FAIL',

  CLEAR_CONTRACT_STATUS:'CLEAR_CONTRACT_STATUS',
}
export const CLINIC={
  GET_CLINIC_REQUEST: 'GET_CLINIC_REQUEST',
  GET_CLINIC_SUCCESS: 'GET_CLINIC_SUCCESS',
  GET_CLINIC_FAIL: 'GET_CLINIC_FAIL',
}
export const AVAILABILITY={
  ADD_AVAILABILITY_REQUEST: 'ADD_AVAILABILITY_REQUEST',
  ADD_AVAILABILITY_SUCCESS: 'ADD_AVAILABILITY_SUCCESS',
  ADD_AVAILABILITY_FAIL: 'ADD_AVAILABILITY_FAIL',

  GET_AVAILABILITY_REQUEST: 'GET_AVAILABILITY_REQUEST',
  GET_AVAILABILITY_SUCCESS: 'GET_AVAILABILITY_SUCCESS',
  GET_AVAILABILITY_FAIL: 'GET_AVAILABILITY_FAIL',
  CLEAR_ERROR_STATUS:"CLEAR_ERROR_STATUS",

  BLOCK_AVAILABILITY_BY_DATE_REQUEST: 'BLOCK_AVAILABILITY_BY_DATE_REQUEST',
  BLOCK_AVAILABILITY_BY_DATE_SUCCESS: 'BLOCK_AVAILABILITY_BY_DATE_SUCCESS',
  BLOCK_AVAILABILITY_BY_DATE_FAIL: 'BLOCK_AVAILABILITY_BY_DATE_FAIL',

  BLOCK_AVAILABILITY_BY_TIME_REQUEST: 'BLOCK_AVAILABILITY_BY_TIME_REQUEST',
  BLOCK_AVAILABILITY_BY_TIME_SUCCESS: 'BLOCK_AVAILABILITY_BY_TIME_SUCCESS',
  BLOCK_AVAILABILITY_BY_TIME_FAIL: 'BLOCK_AVAILABILITY_BY_TIME_FAIL',

  BLOCK_AVAILABILITY_BY_TIME_SLOT_REQUEST: 'BLOCK_AVAILABILITY_BY_TIME_SLOT_REQUEST',
  BLOCK_AVAILABILITY_BY_TIME_SLOT_SUCCESS: 'BLOCK_AVAILABILITY_BY_TIME_SLOT_SUCCESS',
  BLOCK_AVAILABILITY_BY_TIME_SLOT_FAIL: 'BLOCK_AVAILABILITY_BY_TIME_SLOT_FAIL',

  TEAM_AVAILABILITY_LIST_REQUEST:'TEAM_AVAILABILITY_LIST_REQUEST',
  TEAM_AVAILABILITY_LIST_SUCCESS:'TEAM_AVAILABILITY_LIST_SUCCESS',
  TEAM_AVAILABILITY_LIST_FAIL:'TEAM_AVAILABILITY_LIST_FAIL',

  EDIT_SLOT_REQUEST:'EDIT_SLOT_REQUEST',
  EDIT_SLOT_SUCCESS:'EDIT_SLOT_SUCCESS',
  EDIT_SLOT_FAIL:'EDIT_SLOT_FAIL',

  DELETE_SLOT_REQUEST:'DELETE_SLOT_REQUEST',
  DELETE_SLOT_SUCCESS:'DELETE_SLOT_SUCCESS',
  DELETE_SLOT_FAIL:'DELETE_SLOT_FAIL',
  
}
export const MATCHING={
  ADD_MATCHING_REQUEST: 'ADD_MATCHING_REQUEST',
  ADD_MATCHING_SUCCESS: 'ADD_MATCHING_SUCCESS',
  ADD_MATCHING_FAIL: 'ADD_MATCHING_FAIL',

  GET_JOB_DATA_REQUEST: 'GET_JOB_DATA_REQUEST',
  GET_JOB_DATA_SUCCESS: 'GET_JOB_DATA_SUCCESS',
  GET_JOB_DATA_FAIL: 'GET_JOB_DATA_FAIL',

  MY_MATCHING_REQUEST: 'MY_MATCHING_REQUEST',
  MY_MATCHING_SUCCESS: 'MY_MATCHING_SUCCESS',
  MY_MATCHING_FAIL: 'MY_MATCHING_FAIL',

  CLEAR_RESPONSE_STATUS:'CLEAR_RESPONSE_STATUS'
}




