export const API_METHODS = {
  GET: 'get',
  POST: 'post',
  PUT: 'put',
  DELETE: 'delete',
  PATCH: 'patch',
};

export const AUTH = {

  SET_LANGUAGE:"SET_LANGUAGE",

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',

  UPDATE_ACCOUNT_REQUEST:'UPDATE_ACCOUNT_REQUEST',
  UPDATE_ACCOUNT_SUCCESS:'UPDATE_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT_FAIL:'UPDATE_ACCOUNT_FAIL',

  CLEAR_ERROR_STATUS:'CLEAR_ERROR_STATUS',
  CLEAR_RESPONSE_STATUS:'CLEAR_RESPONSE_STATUS',
  CLEAR_ERROR_STATUS_FORGOT_PASSWORD:'CLEAR_ERROR_STATUS_FORGOT_PASSWORD',

  LOGOUT_USER:'LOGOUT_USER',
};

export const BANK={

  BANK_FORM_REQUEST: 'BANK_FORM_REQUEST',
  BANK_FORM_SUCCESS: 'BANK_FORM_SUCCESS',
  BANK_FORM_FAIL: 'BANK_FORM_FAIL',
  CLEAR_BANK_STATUS:'CLEAR_BANK_STATUS'
}

export const CONTRACT={

  CONTRACT_REQUEST: 'CONTRACT_REQUEST',
  CONTRACT_SUCCESS: 'CONTRACT_SUCCESS',
  CONTRACT_FAIL: 'CONTRACT_FAIL',

  CLEAR_CONTRACT_STATUS:'CLEAR_CONTRACT_STATUS',
}
export const CLINIC={
  GET_CLINIC_REQUEST: 'GET_CLINIC_REQUEST',
  GET_CLINIC_SUCCESS: 'GET_CLINIC_SUCCESS',
  GET_CLINIC_FAIL: 'GET_CLINIC_FAIL',
}
export const AVAILABILITY={
  ADD_AVAILABILITY_REQUEST: 'ADD_AVAILABILITY_REQUEST',
  ADD_AVAILABILITY_SUCCESS: 'ADD_AVAILABILITY_SUCCESS',
  ADD_AVAILABILITY_FAIL: 'ADD_AVAILABILITY_FAIL',
}




